/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./../components/layout/AdminLayout.vue')['default']
    BlockchainVerifyBadge: typeof import('./../components/common/BlockchainVerifyBadge.vue')['default']
    BreadcrumbNav: typeof import('./../components/layout/BreadcrumbNav.vue')['default']
    ConfirmDialog: typeof import('./../components/common/ConfirmDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    EmptyState: typeof import('./../components/common/EmptyState.vue')['default']
    ExpireCountdown: typeof import('./../components/common/ExpireCountdown.vue')['default']
    FileUpload: typeof import('./../components/common/FileUpload.vue')['default']
    ImagePreview: typeof import('./../components/common/ImagePreview.vue')['default']
    Pagination: typeof import('./../components/common/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPanel: typeof import('./../components/common/SearchPanel.vue')['default']
    SidebarMenu: typeof import('./../components/layout/SidebarMenu.vue')['default']
    SignaturePad: typeof import('./../components/common/SignaturePad.vue')['default']
    StatusTag: typeof import('./../components/common/StatusTag.vue')['default']
    TopBar: typeof import('./../components/layout/TopBar.vue')['default']
  }
}
